### ISSUE TITLE
Make it work on Linux/Mono

### ISSUE THREAD

**Issue by PawelTroka** [PawelTroka/Computator.NET#25]
Right now according to Travis CI the main problems are references to WPF (which is not supported and will not be supported by Mono) and some resx files (probably directory separators).
See: https://travis-ci.org/PawelTroka/Computator.NET

I think it should not be that hard to resolve those issues (assuming we will just not support Chart3D on Mono, since it is built on top of WPF) but because there are .NET Core, NETStandard and Xamarin coming to support it has rather low priority.

Added: Making it compile is not equal to making it run correctly. We do use p/invoke a lot so resolving this might be more time consuming than estimated before.

- [x] Make it compile
- [x] Get green build
- [x] Make Chart2D work
- [x] Make GSL work
- [x] Make GSL work reliably (eg: even when runinng app for the first time, see #30)
- [x] Make units tests pass without exceptions
- [x] Make integration tests pass without exceptions
- [ ] Make ToolTips work
- [ ] Make Scripting work
- [ ] 'TextEditor' code editor implementation #61
- [ ] Make Complex chart work
- [x] NativeCompiler instance always returns the same compiled assembly on Mono #39

**Comment by PawelTroka** [comment]
It does compile for some time now but we still got runtime errors because of two another issues:

- Chart2D is based on System.Windows.Forms.DataVisualization.Charting which is basically not implemented on Mono and throws exceptions on Mono (#29)
- Missing/not working GSL native libraries for Linux (#30)

**Comment by PawelTroka** [comment]
#29 is done and #30 is close to be done for Linux (then we still need to resolve it for Mac OS)
There are also some other minor issues as we tend to use P/Invoke a lot but those should be resolved soon.

**Comment by PawelTroka** [comment]
We probably will not deliver this in v2.2.
